In [12]:
import numpy as np
file=np.loadtxt("cric.tsv",skiprows=1)
print(file)


[[  0. 100.  78. 342.]
 [  1.  11.  62. 191.]
 [  2.   8.  85. 252.]
 [  3.  71.  24. 307.]
 [  4. 104.  17. 229.]
 [  5.  18. 104. 246.]
 [  6.   8.  76. 226.]
 [  7.  86.  74. 288.]
 [  8.  12.  60. 216.]
 [  9.  25.  90. 304.]
 [ 10.  56.   6. 272.]
 [ 11.  88.  69. 302.]
 [ 12. 147.  65. 312.]
 [ 13. 121. 146. 370.]
 [ 15.  99. 110. 362.]]


In [15]:
Sachin=file[:,1]
print(Sachin)

[100.  11.   8.  71. 104.  18.   8.  86.  12.  25.  56.  88. 147. 121.
  99.]


In [18]:
Dravid=file[:,2]
print(Dravid)

[ 78.  62.  85.  24.  17. 104.  76.  74.  60.  90.   6.  69.  65. 146.
 110.]


In [19]:
Indian=file[:,3]
print(Indian)

[342. 191. 252. 307. 229. 246. 226. 288. 216. 304. 272. 302. 312. 370.
 362.]


In [29]:
Sachin_mean=np.mean(Sachin)
Sachin_median=np.median(Sachin)
print(Sachin_mean)
print(Sachin_median)

63.6
71.0


In [30]:
Dravid_mean=np.mean(Dravid)
Dravid_median=np.median(Dravid)
print(Dravid_mean)
print(Dravid_median)

71.06666666666666
74.0


In [37]:
India_mean=np.mean(Indian)
India_median=np.median(Indian)
print("India mean",India_mean)
print("India median",India_median)

India mean 281.26666666666665
India median 288.0
